# Generated by Django 5.2.11 on 2026-03-03 10:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('date', models.DateField()),
                ('open', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('high', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('low', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('close', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('pe_ratio', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['ticker', 'date'], name='portfolio_s_ticker_2a72d1_idx')],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=16)),
                ('quantity', models.IntegerField()),
                ('avg_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'ticker')},
            },
        ),
    ]
