# Generated by Django 5.2.11 on 2026-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_user_holding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['ticker', 'date'], name='portfolio_s_ticker_2a72d1_idx'),
        ),
    ]
